# Generated by Django 6.0 on 2025-12-13 14:22

from django.db import migrations, models

import sales.models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default=sales.models.generate_order_number, max_length=20, unique=True),
        ),
    ]
